### ISSUE TITLE
Test & verify Windows docker build compatibility.

### ISSUE THREAD

**Issue by evilsocket** [evilsocket/bettercap-ng#28]
The Docker build should be tested (and fixed whenever necessary) as it has been reported to at least run on Windows.

**Comment by kabachook** [comment]
1. Everything described here is only applicable to docker-machine setup on Virtualbox, since my Windows edition is not Pro and no native Hyper-V support 

2. Build fails if we do not add `ENV GOPATH=/gocode` in Dockerfile

3. When I start net.probe it dropped Segmentation fault first but then everything went ok.

![2018-02-06_15-30-13_bash](https://user-images.githubusercontent.com/9118683/35861138-b081bd3c-0b57-11e8-9865-62566b0ba04d.png)

4. `netmon.cap` seems to be working, but I don't know expected output, it just shows me my devices in the network

![2018-02-06_15-58-08_bash](https://user-images.githubusercontent.com/9118683/35861171-cbbc7e16-0b57-11e8-86b1-1fa8478acad1.png)


5. If i start `http-req-dump.cap` it drops an error saying `"iptables": executable file not found in $PATH`, so probably Dockerfile needs fixing

![2018-02-06_15-59-00_bash](https://user-images.githubusercontent.com/9118683/35861181-d2c47a24-0b57-11e8-8f10-70bfbb0e1d2f.png)

**Comment by kabachook** [comment]
BTW, in Virualbox VM you need to add an additional network adapter working in bridge mode to make this work in network your PC is connected to

**Comment by evilsocket** [comment]
@kabachook so the Dockerfile should be fixed, regarding the other errors, could you be able to run a bash session on that container and execute a `ip neigh` ? I'd love to verify the output, for some reasons it looks like it is seg faulting ...

**Comment by kabachook** [comment]
@evilsocket It works totally fine, propably that segfault happened because I chose eth0 as iface, which is virtualbox NAT network adapted (but i'm not sure)
![2018-02-06_17-00-29_bash](https://user-images.githubusercontent.com/9118683/35863271-402d410c-0b5f-11e8-8016-cc276ef2fc6d.png)

**Comment by evilsocket** [comment]
lol i really have no idea then, at some point i'll either install windows on some old pc i have and debug it or just [implement native support](https://stackoverflow.com/questions/11525703/port-forwarding-in-windows) since I discovered it's doable :D

**Comment by kabachook** [comment]
If I put bridge interface(which on my pc is eth1) as iface argument it works, but stops on iptables issue. Give me some commands to try, because I haven't got deep into bettercap yet. Maybe this will help.

**Comment by evilsocket** [comment]
ok, so let's try to fix the iptables issue first ... i'm not familiar with Docker, can you apt-get it somehow? I gave for granted it was there by default, can you see? Any tip on how to fix the Dockerfile to overcome that would be useful, i'm both a docker and windows noob :D

**Comment by kabachook** [comment]
Basically you need to add iptables as dependency in Dockerfile, which can be done by appending iptables to `apk add somedepshere` line. I'll build an image with this and report here, but I have some stuff to do 😅

**Comment by kabachook** [comment]
Also, alpine is a really lightweight image, so pretty everything is removed from it, that's why there is no iptables here

**Comment by evilsocket** [comment]
Added iptables, let me know when you have some time to check :)

**Comment by kabachook** [comment]
It seems to be working now, but I set proxy server on my phone manually, need further testing on arp spoof module
![2018-02-06_18-08-52_conemu64](https://user-images.githubusercontent.com/9118683/35866809-2c041016-0b69-11e8-8196-b8291df1ba9f.png)

**Comment by evilsocket** [comment]
dude you are already helping **a lot**, looking forward to know if/how spoofing works :) **thank you** <3

**Comment by kabachook** [comment]
I will try to test within few days, thank you too for creating this powerful tool <3 ( Actually i'm using linux too and it works ideally)
